FROM maven:3-jdk-8-alpine AS build
ADD . /build
WORKDIR /build
RUN mvn -B -f pom.xml -s /usr/share/maven/ref/settings-docker.xml dependency:resolve
RUN mvn -B -s /usr/share/maven/ref/settings-docker.xml package -DskipTests

FROM java:8-alpine
RUN adduser -Dh /home/gordon gordon
USER gordon
COPY --from=build /build/target/ddev-0.0.1-SNAPSHOT.jar /app/
CMD java -jar /app/ddev-0.0.1-SNAPSHOT.jar --spring.profiles.active=postgres
